### ISSUE TITLE
Lot of AUTH_KEY_UNREGISTERED messages

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#56] opened 2015-05-29 06:09 UTC
There are lot of  AUTH_KEY_UNREGISTERED errors in console output, in windows and linux.

For example:
qint64 Api::accountUpdateStatus(bool): AUTH_KEY_UNREGISTERED

**Comment by realbardia** [comment] 2015-05-29 07:20
Did cutegram works and load messages or contacts? Or It signed out too?
Thank you for reporting

**Comment by Sollex-21412** [comment] 2015-05-29 07:24
Linux:
All works fine, except: contacts avatar, media files won't sending and receiving.

Windows:
Binary from site: After third launch, app gets signed out. No avatars and media files.
Build from git: Same as binary and also doesn't load messages.

**Comment by realbardia** [comment] 2015-05-29 07:34
Cutegram/libqtelegram uses 5 auth keys and IP addresses to connect to the telegram server.
I think one of this auth key (that used for file transferring) expired or changes because of a bug or anything else. Maybe sign-out/sign-in solve problem.
I'll fix it soon.

Windows version has some bugs on some systems (or better to say on some countries). I don't know why it happened. But we are working to fix it soon.

**Comment by Sollex-21412** [comment] 2015-05-29 07:43
Checked on Mac OS 10.10.3 x64
Same behavior as in WIndows.

**Comment by realbardia** [comment] 2015-05-29 12:11
Ok... I found the problem, At least in my system.
The problem is because wrong timezone or clock settings on my operating system. libqtelegram needs correct clock settings.
Is your clock and timezone settings is correct?

**Comment by Sollex-21412** [comment] 2015-05-29 12:13
Yep, they are correct. I'm pretty sure. (GMT +5)

**Comment by Sollex-21412** [comment] 2015-05-29 18:05
My guess: libqtelegram-ae -> utils.cpp -> Utils::getUTime -> clock_gettime
This function (clock_gettime) has different implementation on (linux, mac and win). May be problem is there?

**Comment by realbardia** [comment] 2015-05-29 20:57
I updated cutegram on daily repository and added some command line feature like verbose mode.
Please run cutegram in verbose mode and check the log. If there is a clock/time problem, It'll print an error like:
    Received message has too large difference between client and server dates...

**Comment by Sollex-21412** [comment] 2015-05-30 08:15
<pre>
vpankratov@vpankratov-notebook:~/Development/Cutegram/build/build$ ./cutegram -V
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED" 
qrc:/qml/Cutegram/AccountMessageMedia.qml:186:21: Unable to assign QSizeF to QSize
qrc:/qml/Cutegram/AccountMessageMedia.qml:186:21: Unable to assign QSizeF to QSize
qrc:/qml/Cutegram/AccountMessageMedia.qml:186:21: Unable to assign QSizeF to QSize
qrc:/qml/Cutegram/AccountMessageMedia.qml:186:21: Unable to assign QSizeF to QSize
</pre>

**Comment by Sollex-21412** [comment] 2015-06-01 06:54
MaxcOS console output (part):

<pre>
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "f881cf81e80b77e"
tg.core.session: sending message with sha1 "1777777777777771264215"
tg.core.session: msgId is "556bffa80000001c"
tg.core.outboundpkt: appendInt() "-475607115"  ( "0xffffffffe3a6cfb5" )
tg.core.outboundpkt: appendInt() "342061462"  ( "0x14637196" )
tg.core.outboundpkt: appendLong() "604123467"  ( "0x2402314b" )
tg.core.outboundpkt: appendInt() "43383"  ( "0xa977" )
tg.core.outboundpkt: appendLong() "-8049254137750043757"  ( "0x904b4e022c90c393" )
tg.core.outboundpkt: appendInt() "0"  ( "0x0" )
tg.core.outboundpkt: appendInt() "16384"  ( "0x4000" )
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "f881cf81e80b77e"
tg.core.session: sending message with sha1 "1777777777774574131143"
tg.core.session: msgId is "556bffa800000020"
tg.core.session: connection # 38 received rpc answer 1 with 152 content bytes by session "f881cf81e80b77e"
tg.core.session: processRpcMessage(), len= 152
tg.core.session: received message id "556bffa9569c6001"
tg.core.session: rpcExecuteAnswer(), op = "73f1f8dc"
tg.core.session: workContainer: msgId = "556bffa9569c6001"
tg.core.inboundpkt: fetchInt() 1945237724  ( "0x73f1f8dc" )
tg.core.inboundpkt: fetchInt() 2  ( "0x2" )
tg.core.inboundpkt: fetchLong() 6155294418499491841
tg.core.inboundpkt: fetchInt() 1  ( "0x1" )
tg.core.inboundpkt: fetchInt() 28  ( "0x1c" )
tg.core.session: rpcExecuteAnswer(), op = "ffffffff9ec20908"
tg.core.session: workNewSessionCreated: msgId = "556bffa9569b5801"
tg.core.inboundpkt: fetchInt() -1631450872  ( "0x9ec20908" )
tg.core.inboundpkt: fetchLong() 6155294412751503368
tg.core.inboundpkt: fetchLong() 366782508252198272
tg.core.inboundpkt: fetchLong() 5711082646945078575
tg.core.inboundpkt: fetchLong() 6155294418499557377
tg.core.inboundpkt: fetchInt() 2  ( "0x2" )
tg.core.inboundpkt: fetchInt() 20  ( "0x14" )
tg.core.session: rpcExecuteAnswer(), op = "62d6b459"
tg.core.session: workMsgsAck: msgId = "556bffa9569c5801"
tg.core.inboundpkt: fetchInt() 1658238041  ( "0x62d6b459" )
tg.core.inboundpkt: fetchInt() 481674261  ( "0x1cb5c415" )
tg.core.inboundpkt: fetchInt() 1  ( "0x1" )
tg.core.inboundpkt: fetchLong() 6155294412751503368
tg.core.session: connection # 38 received rpc answer 1 with 200 content bytes by session "f881cf81e80b77e"
tg.core.session: processRpcMessage(), len= 200
tg.core.session: received message id "556bffa95a3fd801"
tg.core.session: rpcExecuteAnswer(), op = "73f1f8dc"
tg.core.session: workContainer: msgId = "556bffa95a3fd801"
tg.core.inboundpkt: fetchInt() 1945237724  ( "0x73f1f8dc" )
tg.core.inboundpkt: fetchInt() 2  ( "0x2" )
tg.core.inboundpkt: fetchLong() 6155294418560585729
tg.core.inboundpkt: fetchInt() 3  ( "0x3" )
tg.core.inboundpkt: fetchInt() 44  ( "0x2c" )
tg.core.session: rpcExecuteAnswer(), op = "fffffffff35c6d01"
tg.core.session: workRpcResult: msgId = "556bffa95a3f9001"
tg.core.inboundpkt: fetchInt() -212046591  ( "0xf35c6d01" )
tg.core.inboundpkt: fetchLong() 6155294412751503388
tg.core.inboundpkt: fetchInt() 558156313  ( "0x2144ca19" )
tg.core.inboundpkt: fetchInt() 401  ( "0x191" )
tg.core.inboundpkt: fetchStr(), len = 21
tg.core.session: error for query "556bffa80000001c"  : 401  : "AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "AUTH_KEY_UNREGISTERED"
</pre>

**Comment by realbardia** [comment] 2015-06-01 06:56
Thank You.
I'll fix it soon :)

**Comment by Sollex-21412** [comment] 2015-06-01 06:56
I can provide full log, but not here ;)

**Comment by realbardia** [comment] 2015-06-01 07:01
Thank You, It's enough currently. 
I'll remove extra (and private) parts of logs from source in the future ;)

**Comment by Sollex-21412** [comment] 2015-06-01 07:12
Cool =) So, will wait for fix ;)

**Comment by Sollex-21412** [comment] 2015-06-01 11:27
Just in case, Windows console output:

<pre>
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "c43a4f7deef36be4"
tg.core.session: sending message with sha1 "1777777777774511042614"
tg.core.session: msgId is "556c402a00000004"
tg.core.outboundpkt: appendInt() "-475607115"  ( "0xffffffffe3a6cfb5" )
tg.core.outboundpkt: appendInt() "342061462"  ( "0x14637196" )
tg.core.outboundpkt: appendLong() "604119127"  ( "0x24022057" )
tg.core.outboundpkt: appendInt() "3175"  ( "0xc67" )
tg.core.outboundpkt: appendLong() "-6489736095850509192"  ( "0xa5efd367a8cccc78" )
tg.core.outboundpkt: appendInt() "0"  ( "0x0" )
tg.core.outboundpkt: appendInt() "16384"  ( "0x4000" )
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "c43a4f7deef36be4"
tg.core.session: sending message with sha1 "11117170242"
tg.core.session: msgId is "556c402a00000008"
tg.core.outboundpkt: appendInt() "-475607115"  ( "0xffffffffe3a6cfb5" )
tg.core.outboundpkt: appendInt() "342061462"  ( "0x14637196" )
tg.core.outboundpkt: appendLong() "604405862"  ( "0x24068066" )
tg.core.outboundpkt: appendInt() "60382"  ( "0xebde" )
tg.core.outboundpkt: appendLong() "-23547750018623248"  ( "0xffac577234e158f0" )
tg.core.outboundpkt: appendInt() "0"  ( "0x0" )
tg.core.outboundpkt: appendInt() "16384"  ( "0x4000" )
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "c43a4f7deef36be4"
tg.core.session: sending message with sha1 "6070613310"
tg.core.session: msgId is "556c402a0000000c"
tg.core.outboundpkt: appendInt() "-475607115"  ( "0xffffffffe3a6cfb5" )
tg.core.outboundpkt: appendInt() "342061462"  ( "0x14637196" )
tg.core.outboundpkt: appendLong() "710510465"  ( "0x2a598781" )
tg.core.outboundpkt: appendInt() "8241"  ( "0x2031" )
tg.core.outboundpkt: appendLong() "-8529010795939007767"  ( "0x89a2dddea69572e9" )
tg.core.outboundpkt: appendInt() "0"  ( "0x0" )
tg.core.outboundpkt: appendInt() "16384"  ( "0x4000" )
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "c43a4f7deef36be4"
tg.core.session: sending message with sha1 "1777777777771317441301"
tg.core.session: msgId is "556c402a00000010"
tg.core.outboundpkt: appendInt() "-475607115"  ( "0xffffffffe3a6cfb5" )
tg.core.outboundpkt: appendInt() "342061462"  ( "0x14637196" )
tg.core.outboundpkt: appendLong() "604124162"  ( "0x24023402" )
tg.core.outboundpkt: appendInt() "77739"  ( "0x12fab" )
tg.core.outboundpkt: appendLong() "6606250568068942201"  ( "0x5bae1de3e6f8c979" )
tg.core.outboundpkt: appendInt() "0"  ( "0x0" )
tg.core.outboundpkt: appendInt() "16384"  ( "0x4000" )
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "c43a4f7deef36be4"
tg.core.session: sending message with sha1 "17073656174"
tg.core.session: msgId is "556c402a00000014"
tg.core.outboundpkt: appendInt() "-475607115"  ( "0xffffffffe3a6cfb5" )
tg.core.outboundpkt: appendInt() "342061462"  ( "0x14637196" )
tg.core.outboundpkt: appendLong() "604123467"  ( "0x2402314b" )
tg.core.outboundpkt: appendInt() "43383"  ( "0xa977" )
tg.core.outboundpkt: appendLong() "-8049254137750043757"  ( "0x904b4e022c90c393" )
tg.core.outboundpkt: appendInt() "0"  ( "0x0" )
tg.core.outboundpkt: appendInt() "16384"  ( "0x4000" )
tg.core.session: Sending query of size 36 to DC 2 at "149.154.167.51" : 443 by session "c43a4f7deef36be4"
tg.core.session: sending message with sha1 "1777777777776227376205"
tg.core.session: msgId is "556c402a00000018"
tg.core.session: connection # 2368 received rpc answer 3198404 with 152 content bytes by session "c43a4f7deef36be4"
tg.core.session: processRpcMessage(), len= 152
tg.core.session: received message id "556c402c2ffba001"
tg.core.session: rpcExecuteAnswer(), op = "73f1f8dc"
tg.core.session: workContainer: msgId = "556c402c2ffba001"
tg.core.inboundpkt: fetchInt() 1945237724  ( "0x73f1f8dc" )
tg.core.inboundpkt: fetchInt() 2  ( "0x2" )
tg.core.inboundpkt: fetchLong() 6155365349236327425
tg.core.inboundpkt: fetchInt() 1  ( "0x1" )
tg.core.inboundpkt: fetchInt() 28  ( "0x1c" )
tg.core.session: rpcExecuteAnswer(), op = "ffffffff9ec20908"
tg.core.session: workNewSessionCreated: msgId = "556c402c2ffac401"
tg.core.inboundpkt: fetchInt() -1631450872  ( "0x9ec20908" )
tg.core.inboundpkt: fetchLong() 6155365339841429504
tg.core.inboundpkt: fetchLong() -3501092719764546168
tg.core.inboundpkt: fetchLong() 3863126602755241455
tg.core.inboundpkt: fetchLong() 6155365349236381697
tg.core.inboundpkt: fetchInt() 2  ( "0x2" )
tg.core.inboundpkt: fetchInt() 20  ( "0x14" )
tg.core.session: rpcExecuteAnswer(), op = "62d6b459"
tg.core.session: workMsgsAck: msgId = "556c402c2ffb9801"
tg.core.inboundpkt: fetchInt() 1658238041  ( "0x62d6b459" )
tg.core.inboundpkt: fetchInt() 481674261  ( "0x1cb5c415" )
tg.core.inboundpkt: fetchInt() 1  ( "0x1" )
tg.core.inboundpkt: fetchLong() 6155365339841429504
tg.core.session: connection # 2368 received rpc answer 3198404 with 200 content bytes by session "c43a4f7deef36be4"
tg.core.session: processRpcMessage(), len= 200
tg.core.session: received message id "556c402c30912001"
tg.core.session: rpcExecuteAnswer(), op = "73f1f8dc"
tg.core.session: workContainer: msgId = "556c402c30912001"
tg.core.inboundpkt: fetchInt() 1945237724  ( "0x73f1f8dc" )
tg.core.inboundpkt: fetchInt() 2  ( "0x2" )
tg.core.inboundpkt: fetchLong() 6155365349246167041
tg.core.inboundpkt: fetchInt() 3  ( "0x3" )
tg.core.inboundpkt: fetchInt() 44  ( "0x2c" )
tg.core.session: rpcExecuteAnswer(), op = "fffffffff35c6d01"
tg.core.session: workRpcResult: msgId = "556c402c3090e801"
tg.core.inboundpkt: fetchInt() -212046591  ( "0xf35c6d01" )
tg.core.inboundpkt: fetchLong() 6155365339841429508
tg.core.inboundpkt: fetchInt() 558156313  ( "0x2144ca19" )
tg.core.inboundpkt: fetchInt() 401  ( "0x191" )
tg.core.inboundpkt: fetchStr(), len = 21
tg.core.session: error for query "556c402a00000004"  : 401  : "AUTH_KEY_UNREGISTERED"
void __thiscall TelegramQml::error(__int64,int,class QString) "AUTH_KEY_UNREGISTERED"
</pre>

**Closed** 2015-06-09 04:56 UTC
Labels: bug
